name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_INSTALLATION_ROOT: C:\vcpkg
    steps:
      - uses: actions/checkout@v2
      - name: Install LASlib
        run: |
          git clone https://github.com/LAStools/LAStools.git
          cd LAStools
          git checkout 653d341833aa2a0b327c20eacee02523faabe255
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=C:\Software
          cmake --build . --config Release --parallel 4
          cmake --install .
      - name: Remove system vcpkg (to ensure support for binary caching)
        shell: 'bash'
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"
      - name: Install latest vcpkg (to ensure support for binary caching)
        run: |
          cd C:\
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat
      - name: Install CGAL & Boost & glm
        run: |
          echo $env:VCPKG_INSTALLATION_ROOT
          cd C:\
          cd vcpkg 
          .\vcpkg.exe install cgal boost-geometry glm
      - name: Install fetch
        run: |
          Invoke-WebRequest https://github.com/gruntwork-io/fetch/releases/download/v0.3.7/fetch_windows_amd64.exe -OutFile fetch.exe
      - name: Install latest Geoflow
        run: |
          .\fetch.exe --repo="https://github.com/geoflow3d/geoflow" --tag=">=0.1.4" --release-asset="Geoflow-win64.exe" .\
          .\Geoflow-win64.exe /S
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_INSTALL_PREFIX=C:\Software -DGFP_WITH_PDAL=OFF
          cmake --build . --target gfp_buildingreconstruction --parallel 4 --config Release
      - name: collect dll's
        run: |
          mkdir gfp-building-reconstruction
          mkdir gfp-building-reconstruction\deps
          cp build\Release\gfp_buildingreconstruction.dll gfp-building-reconstruction\
          cp C:\vcpkg\installed\x64-windows\bin\mpfr.dll gfp-building-reconstruction\deps\
          cp C:\vcpkg\installed\x64-windows\bin\mpir.dll gfp-building-reconstruction\deps\
      - name: Create artifact
        uses: actions/upload-artifact@master
        with:
          name: gfp-building-reconstruction-win64
          path: gfp-building-reconstruction
