name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LASlib
        run: |
          git clone https://github.com/LAStools/LAStools.git
          cd LAStools
          git checkout 653d341833aa2a0b327c20eacee02523faabe255
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=C:\Software
          cmake --build . --config Release --parallel 4
          cmake --install .
      - name: Install dependencies
        run: |
          echo $env:VCPKG_INSTALLATION_ROOT
          $env:VCPKG_DEFAULT_TRIPLET="x64-windows"
          vcpkg install cgal gdal boost-geometry
      - name: Install Geoflow
        run: |
          Invoke-WebRequest https://github.com/geoflow3d/geoflow/releases/download/v0.1.1/Geoflow-0.1.1-win64.exe -OutFile geoflow-setup.exe
          .\geoflow-setup.exe /S
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=C:\Software -DGFP_WITH_PDAL=OFF
          cmake --build . --target gfp_building_reconstruction --parallel 4 --config Release
      - name: Create artifact
        uses: actions/upload-artifact@master
        with:
          name: gfp-buildng-reconstruction-win64
          path: build/Release/gfp_building_reconstruction.dll
